package com.culinarycoordinator.orders.controller;

import com.culinarycoordinator.orders.common.StandardResponse;
import com.culinarycoordinator.orders.dto.CreateOrderRequest;
import com.culinarycoordinator.orders.dto.OrderResponse;
import com.culinarycoordinator.orders.service.OrderService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/orders")
@Tag(name = "Orders", description = "Manages the orders generated by the users.")
public class OrderController {

    private final OrderService service;

    public OrderController(OrderService service) {
        this.service = service;
    }

    @PostMapping
    @Operation(summary = "Create Order", description = "Creates new order")
    public StandardResponse<OrderResponse> create(
            @RequestBody @Valid CreateOrderRequest request) {

        return StandardResponse.success(
                "Order created successfully",
                service.create(request)
        );
    }

    @GetMapping("/{id}")
    @Operation(summary = "Get order", description = "Get the order info based on id")
    public StandardResponse<OrderResponse> get(@PathVariable Long id) {
        return StandardResponse.success(
                "Order fetched successfully",
                service.getById(id)
        );
    }
}
